<<<<<<< HEAD
<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="2" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="6094" started-at="2018-10-16T18:28:25Z" finished-at="2018-10-16T18:28:31Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="6094" started-at="2018-10-16T18:28:25Z" finished-at="2018-10-16T18:28:31Z">
      <class name="tests.LoginCRMTest">
        <test-method status="PASS" signature="setupTest()[pri:0, instance:tests.LoginCRMTest@6404f418]" name="setupTest" is-config="true" duration-ms="23" started-at="2018-10-16T18:28:25Z" finished-at="2018-10-16T18:28:25Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setupTest -->
        <test-method status="FAIL" signature="LoginTest()[pri:1, instance:tests.LoginCRMTest@6404f418]" name="LoginTest" duration-ms="1306" started-at="2018-10-16T18:28:25Z" finished-at="2018-10-16T18:28:26Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [CRMPRO] but found [#1 Free CRM software in the cloud for sales and service]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [CRMPRO] but found [#1 Free CRM software in the cloud for sales and service]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at tests.LoginCRMTest.LoginTest(LoginCRMTest.java:48)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginTest -->
        <test-method status="FAIL" signature="verifyTitleTest()[pri:2, instance:tests.LoginCRMTest@6404f418]" name="verifyTitleTest" duration-ms="3385" started-at="2018-10-16T18:28:26Z" finished-at="2018-10-16T18:28:29Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [CRMPRO] but found [#1 Free CRM software in the cloud for sales and service],
expected [CRMPRO] but found [#1 Free CRM software in the cloud for sales and service],
expected [#1 Free CRM software in the cloud for sales and service] but found [CRMPRO]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [CRMPRO] but found [#1 Free CRM software in the cloud for sales and service],
expected [CRMPRO] but found [#1 Free CRM software in the cloud for sales and service],
expected [#1 Free CRM software in the cloud for sales and service] but found [CRMPRO]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at tests.LoginCRMTest.verifyTitleTest(LoginCRMTest.java:65)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyTitleTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:tests.LoginCRMTest@6404f418]" name="tearDown" is-config="true" duration-ms="1325" started-at="2018-10-16T18:28:29Z" finished-at="2018-10-16T18:28:31Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- tests.LoginCRMTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
=======
<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="0" ignored="0" total="2" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="8157" started-at="2018-10-17T11:11:52Z" finished-at="2018-10-17T11:12:00Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="8157" started-at="2018-10-17T11:11:52Z" finished-at="2018-10-17T11:12:00Z">
      <class name="tests.LoginCRMTest">
        <test-method status="PASS" signature="setupTest()[pri:0, instance:tests.LoginCRMTest@2dc54ad4]" name="setupTest" is-config="true" duration-ms="17" started-at="2018-10-17T11:11:52Z" finished-at="2018-10-17T11:11:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setupTest -->
        <test-method status="PASS" signature="LoginTest()[pri:1, instance:tests.LoginCRMTest@2dc54ad4]" name="LoginTest" duration-ms="6677" started-at="2018-10-17T11:11:52Z" finished-at="2018-10-17T11:11:59Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginTest -->
        <test-method status="PASS" signature="verifyTitleTest()[pri:2, instance:tests.LoginCRMTest@2dc54ad4]" name="verifyTitleTest" duration-ms="1290" started-at="2018-10-17T11:11:59Z" finished-at="2018-10-17T11:12:00Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyTitleTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:tests.LoginCRMTest@2dc54ad4]" name="tearDown" is-config="true" duration-ms="134" started-at="2018-10-17T11:12:00Z" finished-at="2018-10-17T11:12:00Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- tests.LoginCRMTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
>>>>>>> branch 'master' of https://github.com/vadherhemant/HemantFramework.git
